sudo: required

language: node_js

node_js:
  - "8"

dist: trusty

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - npm install coveralls

script:
  - npm run test
  - npm run e2e

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: www
  on:
    branch: master
